[build]
target = "bpfel-unknown-none"

[target.bpfel-unknown-none]
linker = "bpf-linker"
rustflags = [
    "-C", "debuginfo=2",
    "-C", "debug-assertions=no",
    "-C", "overflow-checks=no",
    "-C", "opt-level=2",
]
